### ISSUE TITLE
Method and header filtering don't work for me

### ISSUE THREAD

**Issue by prein** [probelabs/goreplay#109]
Hi, 

The tool is great and very useful, however I have trouble using filters. I'm running gor with folllowing syntax:
gor --input-raw :80 --output-file=sample1.gor --output-http-method GET --output-http-header-filter Host:^www.foo.com

In sample1.gor I can find POST requests as well as requests with every value of Host: header there was.

**Comment by nnaoumov** [comment]
+1 
Is this the case for output-http-url-regexp too?

**Comment by buger** [comment]
Yes, but do not forget that even if it saves all requests to the file, when you actually output this requests to staging env you still can use output-http filters.

**Comment by nnaoumov** [comment]
I see, well that's good. It does still make a big difference in the size of the files - especially in my case I am interested in capturing requests for a particular url that would be a very small percentage of the traffic so instead of having file(s) of a few MB I'll be collecting/moving around several GB worth of data.

**Comment by buger** [comment]
I'm working on solution right now, but it will be quite different.
